### ISSUE TITLE
Turn the "python" widget into a REPL interactive shell

### ISSUE THREAD

**Issue by yungyuc** [solvcon/solvcon#104]
Currently the viewer is using a primitive widget to take Python code to run and it is not easy to use:

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/399122/179379311-7bda9788-ff55-478f-86fc-5461caf8a45d.png">

There should be a REPL widget working like the Python REPL or iPython.

- [x] Add an interactive Python command console #145
- [x] Remove the Python text box at the right-hand side #146
- [x] Redirect the buffered outputs to the console display, see discussions in https://github.com/solvcon/modmesh/pull/144#discussion_r1014557732 @tigercosmos
  - #148 
- ~~Support <shift-enter> to type  more than one line.~~
- ~~Add a `run` button for the command line, it will be more straightforward.~~
  - It might not be the best way for the console UI.  Need more thoughts.

**Comment by tai271828** [comment]
REPL is a best-practice commonly seen in this use case. +1 to the idea.

**Comment by yanagiragi** [comment]
LGTM. How about also provide an another feature to load *.py and execute it in the viewer?

**Comment by yungyuc** [comment]
> LGTM. How about also provide an another feature to load *.py and execute it in the viewer?

Agree.  It could be done by extending the new "app" sub system (#100).

**Comment by yungyuc** [comment]
@tigercosmos As we discussed in https://github.com/solvcon/modmesh/pull/144#discussion_r1014557732 , we should redirect the buffered outputs to the console display.

**Comment by tigercosmos** [comment]
@yungyuc yes, I will work on it.
I think we can also add the following as TODOs
- add a `run` button for the command line, it will be more straightforward.
- support <shift-enter> to go to the next line

**Comment by yungyuc** [comment]
> @yungyuc yes, I will work on it.
> 
> I think we can also add the following as TODOs
> 
> - add a `run` button for the command line, it will be more straightforward.
> 
> - support <shift-enter> to go to the next line

Thanks.  Agree.  Items added.

**Comment by yungyuc** [comment]
@tigercosmos There is one remaining part unfinished:

* Support to type more than one line.

Do you plan to finish it?

**Comment by tigercosmos** [comment]
@yungyuc nit for now, I will unassign myself

**Comment by yungyuc** [comment]
> @yungyuc nit for now, I will unassign myself

Thanks for letting me know.  I am closing it.
