### ISSUE TITLE
Cmake setting for QT

### ISSUE THREAD

**Issue by tigercosmos** [solvcon/solvcon#149]
for Linux, I always need to add the line manually to make QT work. Maybe have a variable to specify the QT path and also try to guess where is QT?

```
set(CMAKE_PREFIX_PATH "/home/user/Qt/6.3.2/gcc_64/lib/cmake")
```

**Comment by yungyuc** [comment]
It is hard to make a right guess on every platform, and it is recommended to control it from build system argument, like: https://github.com/solvcon/modmesh/blob/e40e0d9fd7c5d16963425518a31d24e7df86e151/Makefile#L34

It also helps us to make parallel builds of different versions of Qt.

I will leave this issue open for a while for further discussions, but it looks like a non-issue.

**Comment by yungyuc** [comment]
It's probably not impossible to augment the path search on top of the Qt cmake library.  @tigercosmos any thoughts?

**Comment by tigercosmos** [comment]
maybe we could let Cmake give hint, like "QT path cannot found, please try to set `set(CMAKE_PREFIX_PATH "/home/user/Qt/6.3.2/gcc_64/lib/cmake")` in the Cmake file"

**Comment by yungyuc** [comment]
Printing a log message is a good idea, but I think it should be to suggest command line argument rather than modifying `CMakeLists.txt` (intrusive):

```
cmake -DCMAKE_PREFIX_PATH=/path/to/qt/6.2.3/macos 
```

It would take some experiments and discussions to come up with a best practice.  I do it with my `setup.mk` and IDE settings.

**Comment by tigercosmos** [comment]
@yungyuc so let's print a message as a workaround for now?

**Comment by yungyuc** [comment]
Sounds good to me.
