### ISSUE TITLE
Study how to use vertex buffer of Qt3D

### ISSUE THREAD

**Issue by yungyuc** [solvcon/solvcon#171]
See https://doc.qt.io/qt-6/qt3dcore-qattribute.html#vertexSize-prop and #167, #170.  We should understand what does `setVertexSize()` do and use it in a right way.

**Comment by yungyuc** [comment]
@j8xixo12 could you help take a deeper look at the issue?

**Comment by j8xixo12** [comment]
@yungyuc  ok!
I’ll take a look at this issue

**Comment by yungyuc** [comment]
> @yungyuc  ok!
> 
> I’ll take a look at this issue

Thanks!  It seems to be more complex than we thought.

**Comment by yungyuc** [comment]
The study has been done.
