### ISSUE TITLE
CI for windows began to fail

### ISSUE THREAD

**Issue by tai271828** [solvcon/solvcon#182]
I noticed CI began to fail since yesterday.

- https://github.com/solvcon/modmesh/actions/runs/3725891142
- https://github.com/solvcon/modmesh/actions/runs/3733775280

**Comment by tai271828** [comment]
btw, the CI for my personal fork failed since 3 days ago https://github.com/tai271828/modmesh/actions/runs/3720939984

**Comment by yungyuc** [comment]
It's being discussed at https://discord.com/channels/730297880140578906/730393342818648204/1054553931776278618
