### ISSUE TITLE
Enhance modmesh Euler 1D app GUI

### ISSUE THREAD

**Issue by j8xixo12** [solvcon/solvcon#202]
Euler 1D GUI need to be enhanced.

Feature list:
- [x] Save figure button.
- [x] Layout rearrangement with drag and drop.
- [x] All in one plot and grid layout switch button.

**Comment by yungyuc** [comment]
As it is being developed, could you please list all the items that you would like to include in the issue?

**Comment by j8xixo12** [comment]
Currently the following feature are under development:
1. Save figure button. (Done)
2. Layout rearrangement with drag and drop. (Done)
3. All-in one plot and grid layout switch button. (Working in process)

**Comment by yungyuc** [comment]
Could you add the list directly in the issue body and use checkboxes to track them?

**Comment by yungyuc** [comment]
The new visualizer added in #210 does not look right:

<img width="1541" alt="image" src="https://user-images.githubusercontent.com/399122/230759330-ed35203b-c48c-432a-ac81-7e20cd24bb40.png">

We can use a new issue to fix it.  I am closing this one.
