### ISSUE TITLE
euler1d app GUI does not look right

### ISSUE THREAD

**Issue by yungyuc** [solvcon/solvcon#212]
The new visualizer added in #210 (issue #202) does not look right:

<img width="1541" alt="image" src="https://user-images.githubusercontent.com/399122/230759391-0dd90af1-e670-4516-aa0d-486069113af2.png">

@j8xixo12 Could you take a look?

# Update on Oct 20

See https://github.com/solvcon/modmesh/issues/212#issuecomment-1772420049

- [x] Visualization should look good in both sub-window and (standalone) popped-out window.
- [x] The main window size should be set to accommodate the sub-window.

**Comment by j8xixo12** [comment]
The `Runtimeerror: Internal C++ object (pySide6.QtGui.QtGui)` was caused by #202, Euler1d need to access c++ side Qt object and this Qt object need to by managed by `shiboken6` or it will raise runtime error.

This issue has fixed by https://github.com/solvcon/modmesh/commit/93b751574f43288e67b70f1d0655ea4982630773

**Comment by yungyuc** [comment]
The plots still looks as I shown above: very compressed and inconsistent.  If it looks better on your side, could you please share how it looks and how do you make it look better, @j8xixo12 ?

**Comment by j8xixo12** [comment]
No it doesn't looks better on my side.
<img width="1112" alt="截圖 2023-05-22 上午8 25 03" src="https://github.com/solvcon/modmesh/assets/21517083/19013d21-dc2f-4aa3-8bbe-b15947813a48">

I try to enlarge the sub window size to 1000 x 1000, it looks better, but some part be hidden below the console window.
<img width="1112" alt="截圖 2023-05-22 上午8 26 31" src="https://github.com/solvcon/modmesh/assets/21517083/e99a3711-e4d9-4195-a7e0-dd54e79cc57e">

We can scroll down to see the hidden part, but I'm not sure is that a good way to adjust UI.

**Comment by yungyuc** [comment]
Thanks for confirming, @j8xixo12 .  We need to do a better job for the plotting, before we can do anything serious for mesh.  Let's discuss more.

**Comment by yungyuc** [comment]
I think two things need to be improved:
1. Visualization should look good in both sub-window and (standalone) popped-out window.
2. The main window size should be set to accommodate the sub-window.

**Comment by j8xixo12** [comment]
I will do the following items to improve the euler1d app UI layout:
- [x] Using UI to configure solver
- [x] Add simulation control into UI
- [x] Using [PUI](https://github.com/buganini/PUI) to create the following UI layout
<img width="697" alt="截圖 2024-01-07 晚上9 36 36" src="https://github.com/solvcon/modmesh/assets/21517083/cbd9258e-5da7-4546-9b6f-59aa7d710389">

- [ ] Migrate the euler1d app to the new UI layout
- [ ] Make solver setting become dockable window
- [ ] Make plotting area become a sub-window

**Comment by yungyuc** [comment]
Thanks, @j8xixo12 .  I'd like everything fits in the main window.  The setting and bottoms may be dockable.  The plotting area should be a sub-window that may be popped up.  Is in the plan?

**Comment by j8xixo12** [comment]
@yungyuc No, these features are not in the plan.
Let setting and plotting area become dockable window maybe a good ideas, I will put it in my plan !

**Comment by yungyuc** [comment]
And the plotting area should be made as a sub-window.  A standalone (only) window does not offer good user experience.  Could you please also add to your plan?  (Feel free to amend your previous comment, e.g.,

---

Additional work:

1. ...
2. ...

**Comment by j8xixo12** [comment]
> I will do the following items to improve the euler1d app UI layout:
> 
> * [x]  Using UI to configure solver
> * [x]  Add simulation control into UI
> * [x]  Using [PUI](https://github.com/buganini/PUI) to create the following UI layout
> 
> <img alt="截圖 2024-01-07 晚上9 36 36" width="697" src="https://private-user-images.githubusercontent.com/21517083/294761446-cbd9258e-5da7-4546-9b6f-59aa7d710389.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NzQzNDMsIm5iZiI6MTcwNDY3NDA0MywicGF0aCI6Ii8yMTUxNzA4My8yOTQ3NjE0NDYtY2JkOTI1OGUtNWRhNy00NTQ2LTliNmYtNTlhYTdkNzEwMzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDAwMzQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNzc0NTg3ZDhhN2QyODgzZmVlNjBhZDdlYjY1NTJlMzQ5NDJmMzVlZGEzYWM2ZGY2MzRlY2YwNWY3YzhiYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZyMEG6B7JYrUI8VtiM6F4jNUd9NzkdndNEDPfAKWpbw">

> * [ ]  Migrate the euler1d app to the new UI layout
> * [ ]  Make solver setting become dockable window
> * [ ]  Make plotting area become a sub-window

I have added new items to my plan, that is making solver setting become a dockable window and plot area as a sub-window.

**Comment by yungyuc** [comment]
The plot area should be a sub-window, not a dockable window.

**Comment by j8xixo12** [comment]
> Thanks, @j8xixo12 . I'd like everything fits in the main window. The setting and bottoms may be dockable. The plotting area should be a sub-window that may be popped up. Is in the plan?

I had thought the sub-window that may be popped up is equivalent to a dockable window.
Because the PySide6 sub-window can not be popped up.

I have updated my plan.

**Comment by j8xixo12** [comment]
The item of **Using UI to configure solver** also should be linked to https://github.com/solvcon/modmesh/issues/247, and the item of **Add simulation control into UI** should be linked to https://github.com/solvcon/modmesh/issues/243.

**Comment by yungyuc** [comment]
> > Thanks, @j8xixo12 . I'd like everything fits in the main window. The setting and bottoms may be dockable. The plotting area should be a sub-window that may be popped up. Is in the plan?
> 
> I had thought the sub-window that may be popped up is equivalent to a dockable window. Because the PySide6 sub-window can not be popped up.

You are right that Qt sub-window cannot pop out.  IIUC, in QT, A dockable window differs from a sub-window.

It is also needed to find out how to pop out a sub-window.  To make things useful they will get quite complex.  So a plan and constant alignment are very much needed.

**Comment by j8xixo12** [comment]
@yungyuc My next plan is to work on a Python dockable window.

This plan will be separated into 2 part:
1. Wrap `addDockWidget` C++ api to Python.
2. Refine Euler1d app with dockable widget, the app layout will include a dockable configuration window and sub-window for plotting area.

I will file a pr for wrapping `addDockWidget` first, which is the first item of my plan.

**Comment by yungyuc** [comment]
For wrapping `addDockWidget`, do you plan to use PySide6 or PUI?

**Comment by j8xixo12** [comment]
Sorry, I just found that the viewer already wrapped `mainWindow` to python.
So I can access `addDockWidget` in python, therefore wrapping `addDockWidget` to python is not necessary.
For dockable widget I plan to use PUI.

**Comment by j8xixo12** [comment]
> @yungyuc My next plan is to work on a Python dockable window.
> 
> This plan will be separated into 2 part:
> 
> 1. Wrap `addDockWidget` C++ api to Python.
> 2. Refine Euler1d app with dockable widget, the app layout will include a dockable configuration window and sub-window for plotting area.
> 
> I will file a pr for wrapping `addDockWidget` first, which is the first item of my plan.

Update my plan:
Sperate `Euler1DApp` into 2 widgets, one is configuration window as a dockable widget the other is plotting area as a sub-window.

**Comment by j8xixo12** [comment]
![Image](https://github.com/solvcon/modmesh/assets/21517083/9ea6bf2c-a88a-4edd-a497-cd35eec53564)

Here is the latest GUI layout of Euler1D app, but still has something to be enhanced:
1. Poor plotting efficiency
2. Can not select which data to plot
3. User can not customize data line appearance

The next plan is:
1. Speed up plotting efficiency by blitting.
2. Add a button on toolbar to popup a configure window that allows user to customize data line appearance
    - Popup window contains a table, user can select which data line should be plotted and customize data line appearance

**Comment by yungyuc** [comment]
@j8xixo12 Drawing performance issue may not prevent you from making a PR for the new features.  Could you please first prepare a PR for it?  Depending on the amount of code changed, it may need to be broken into multiple PR for review.

**Comment by yungyuc** [comment]
@j8xixo12 while preparing for the new GUI PR, could you please find @q40603 to learn how to use his profiler to help you find the performance hotspots?

**Comment by j8xixo12** [comment]
> [@j8xixo12](https://github.com/j8xixo12) Drawing performance issue may not prevent you from making a PR for the new features. Could you please first prepare a PR for it? Depending on the amount of code changed, it may need to be broken into multiple PR for review.

I will file a PR for the new GUI in the next few days.
I also plan to find @q40603 to learn how to use the profiler in this week.

**Comment by yungyuc** [comment]
Fixed by #271
