### ISSUE TITLE
CI fail to find Numpy with pip install

### ISSUE THREAD

**Issue by j8xixo12** [solvcon/solvcon#213]
CI fail to find `Numpy`, due to latest `pip` (23.1.0),
https://github.com/solvcon/modmesh/actions/runs/4724133935/jobs/8380959174#step:7:123

**Comment by j8xixo12** [comment]
It is hard to debug inside `pip`, the temporary solution of this issue is to use older pip (23.0.1) to install modmesh in CI test case.

**Comment by yungyuc** [comment]
It seems to fail again: https://github.com/solvcon/modmesh/actions/runs/4735343779/jobs/8405439558

Maybe we need to fix the `setup.py`.

**Comment by j8xixo12** [comment]
In order to fix #220, it will encounter symbol resolution issue in GitHub Actions environment and let CI fail.
I has fixed this in **ubuntu** and **macOS** environments but **Windows** environment still need some time to fix it.

**Comment by yungyuc** [comment]
Thanks @j8xixo12 .  What about creating a PR to discuss possible ways to move forward?

**Comment by j8xixo12** [comment]
> Thanks @j8xixo12 . What about creating a PR to discuss possible ways to move forward?

@yungyuc I jsut file a PR #221.

**Comment by yungyuc** [comment]
This issue is fixed with #222 .  We track the new windows CI failure with #220.
