### ISSUE TITLE
Convert Plot3D structure mesh to modmesh unstructured mesh data file

### ISSUE THREAD

**Issue by yungyuc** [solvcon/solvcon#235]
[Plot3D](https://en.wikipedia.org/wiki/PLOT3D_file_format) is a structure grid data format.  In two-dimensional space, the structured grid can be converted into quadrilateral spatial mesh.  In three-dimensional space, the structured grid can be converted into hexagonal mesh.

There should be a command-line utility to convert the Plot3D mesh file, including boundary condition specification, into solvcon/modmesh internal data (in memory), and the associated data file.

There should be underneath C++ library and Python wrapper for the converting implementation.

**Comment by EN-Chou** [comment]
Hi @yungyuc ,
I wonder what is the target output of the conversion? Is it [MSH file format](https://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format) the target?

**Comment by EN-Chou** [comment]
As for Plot3D-related utilities:
1. [nasa/Plot3D_utilities](https://github.com/nasa/Plot3D_utilities) is a Python library for reading, writing, finding connectivity for plot3d files, yet it doesn't seem to have a underneath C++ library. 
2. [PLOT3D, Version 4.1](https://software.nasa.gov/software/ARC-14400-1) run on command prompt as described in [PLOT3D user's manual](https://ntrs.nasa.gov/citations/19900013774). I wonder whether this is the command-line utiility you are referring to. I cannot get access to this software to learn about how it is implemented so far, maybe because its US-Release only.
3. [p3d2gmsh](https://github.com/mrklein/p3d2gmsh) and [plot3d_to_gmsh](https://github.com/ashishbhole/plot3d_to_gmsh) converts Plot3D into [MSH file format](https://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format), via python/FORTRAN respectively.

**Comment by EN-Chou** [comment]
I am not clear about the proper extensions of grid files and the format of Plot3D so far. It seems that two file formats we here concern are grid file(`.xyz`, e.g, [VSPT_ASCII.xyz(78.45MB)](https://nasa-public-data.s3.amazonaws.com/plot3d_utilities/VSPT_ASCII.xyz)), which contain the coordinates of the solution grids and solution file; and solution files(`.q`), which contain typically density(scalar), momentum(vector) and energy(scalar). So far, I have not found a sample of q file. Yet, documentation of [INS3D](https://www.nas.nasa.gov/publications/software/docs/ins3d/index.html) describe its input files via other extensions, which are `xyz.dat` or `xyz.fmt`. As for the Plot3D format, I suppose "Chapter 8 Data File Format" of [PLOT3D user's manual](https://ntrs.nasa.gov/citations/19900013774) are not the format of corresponding files, instead, the FORTRAN code to read these formatted files. [Plot3d File Format for Grid and Solution Files](https://www.grc.nasa.gov/WWW/wind/valid/plot3d.html) also describe the format through similar method. [Plot3D 1.6.0 documentation](https://nasa.github.io/Plot3D_utilities/_build/html/notes/plot3d.html) introduce the format of grid file by commenting the xyz file, yet I did not find q file introduction.

**Comment by yungyuc** [comment]
> Hi @yungyuc ,
> 
> I wonder what is the target output of the conversion? Is it [MSH file format](https://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format) the target? 

The destination format should be the file format representing the data object for the `StaticMesh`.  It is available in the previous project (solvcon) but has not yet been defined for modmesh.  It should be ported from solvcon to modmesh.

**Comment by EN-Chou** [comment]
@yungyuc, I originally have questions about file extensions and solution file, I'll ignore them at this moment for their indirect correlations to this issue. I suppose that [Plot3d File Format for Grid and Solution Files](https://www.grc.nasa.gov/WWW/wind/valid/plot3d.html) provides sufficient information to illustrate PLOT3D file format, the next step for me is to learn about the modmesh data structure and then work on the converter(parser), [su2code/MeshTools](https://github.com/su2code/MeshTools) may be a potential reference. Also, I had a wrong understanding of [mesh data conversion](https://yyc.solvcon.net/en/latest/nsd/project/project.html#mesh-data-conversion), the proposal originally made does not align with the goal, I'll make a update of the proposal hopefully by tomorrow.

**Comment by yungyuc** [comment]
Thanks @EN-Chou for the update. Figuring out the modmesh data structure is a reasonable action to take.  I would suggest to start working on a PR to load a (very) simple Plot3D grid file to modmesh and plot it in the viewer.  What do you think?

If it looks like a good way to move forward, could you please make an estimate for when you can come up with a prototype for review?

**Comment by EN-Chou** [comment]
> Thanks @EN-Chou for the update. Figuring out the modmesh data structure is a reasonable action to take. I would suggest to start working on a PR to load a (very) simple Plot3D grid file to modmesh and plot it in the viewer. What do you think?
> 
> If it looks like a good way to move forward, could you please make an estimate for when you can come up with a prototype for review?

I am not sure how much work and how long it will take for me figure out modmesh data structure and the converter. But I have 3 days to work on this before 9/30, I'll say 9/30 for now, but I would like to ask for your advice.

**Comment by yungyuc** [comment]
> I am not sure how much work and how long it will take for me figure out modmesh data structure and the converter. But I have 3 days to work on this before 9/30, I'll say 9/30 for now, but I would like to ask for your advice.

3 days are more than sufficient for a quick prototype.

**Comment by yungyuc** [comment]
The loading part of the request in this issue has been addressed by #333.

This issue has been idling for a while.  I am closing it.  A new issue can be created when we need the writing capability.
