### ISSUE TITLE
Add basic flow control widgets for euler1d

### ISSUE THREAD

**Issue by yungyuc** [solvcon/solvcon#243]
Following up #242, the euler1d app should have basic control widgets.  It includes start, stop, pause, restart, etc.

**Comment by j8xixo12** [comment]
@yungyuc could you please help to set me as the assignee of this issue ?
I will take care of this issue.

**Comment by yungyuc** [comment]
> @yungyuc could you please help to set me as the assignee of this issue ? I will take care of this issue.

Done.  Thanks.

**Comment by yungyuc** [comment]
@j8xixo12 I think this issue has been resolved.  Could you please find all associated PRs and list them in comment here?

**Comment by j8xixo12** [comment]
The basic flow control for euler1d has been completed by #250 and #253

**Comment by yungyuc** [comment]
Thanks.  Let me close this issue.
