### ISSUE TITLE
Make PUI parameter editing available in the Euler1D app in the modmesh viewer

### ISSUE THREAD

**Issue by yungyuc** [solvcon/solvcon#247]
In #246 , @buganini successfully added prototype code to call PUI from within modmesh.  Some C++ code was added in the modmesh build system and it does not break.

We should go ahead to make PUI useable from modmesh apps.  This ticket is to track the first batch of work: Add PUI parameter editing to Euler1D app.

**Comment by j8xixo12** [comment]
For Euler1D app, I will try to integrate with PUI to setup parameters, the following parameters are the ones I have compiled to be used as input parameters:
1. Gamma
2. The pressure on the left side of diaphragm
3. The density on the left side of diaphram
4. The pressure on the right side of diaphragm
5. The density on the right side of diaphragm
6. node number
7. GUI step interval
8. Solver time step
9. Solver maximum step number

**Comment by yungyuc** [comment]
@j8xixo12 IIUC you have fixed this issue.  Could you please find the associate PR(s)?

**Comment by j8xixo12** [comment]
The PUI has been integrated with modmesh by #271

**Comment by j8xixo12** [comment]
The GUI user experience has been enhanced by #308

**Comment by yungyuc** [comment]
Thanks, @j8xixo12.  It seems that the work for this issue is done.  I am closing it.  Feel free to reopen if needed.
