### ISSUE TITLE
PySide6 can not be imported at macos-13 image

### ISSUE THREAD

**Issue by j8xixo12** [solvcon/solvcon#277]
When the CI uses the macos-13 image, PySide6 cannot be imported successfully.

The GitHub actions log: https://github.com/solvcon/modmesh/actions/runs/7952874439/job/21708086025?pr=271#step:12:103

**Comment by j8xixo12** [comment]
@terrychan999 can you help to file a PR to fix this issue ?

**Comment by terrychan999** [comment]
I've just made a PR, thanks for the reminder.

**Comment by j8xixo12** [comment]
Since macos-13 issue has fixed by @terrychan999. Let's close this issue!
