### ISSUE TITLE
Columnar group of arrays

### ISSUE THREAD

**Issue by yungyuc** [solvcon/solvcon#28]
`SimpleArray` currently supports only fundamental types.  Before supporting struct arrays, I would like to explore how it can support columnar groups of arrays.

The columnar groups organize arrays in the following way:

```cpp
struct StructOfArray
{
    SimpleArray<int32_t> m_field1;
    SimpleArray<double> m_field2;
};
```

This is also the so-called structure of arrays.  If we treat the fields as the "rows" in a 2D array, the data in the group are organized like the "column-major" format of 2D arrays.  This is why we use "columnar" to describe this kinds of data structure.

We hope modmesh provides a nice way to support the columnar data structure in C++ and allow easy access in Python, while it is possible to manually write code to construct the above `StructOfArray`, but the code is ad hoc and convoluted.

# References

* [Arrow Columnar Format](https://arrow.apache.org/docs/format/Columnar.html)

**Comment by yungyuc** [comment]
@tai271828 Do you have an idea for the implementation plan?

**Comment by tai271828** [comment]
No, simply assigning myself as a reminder. Maybe I should use subscription instead.

> @tai271828 Do you have an idea for the implementation plan?

**Comment by tai271828** [comment]
Status update from my side: build and installation looks good with Ubuntu 20.04 for passing pytest.

```
ubuntu@ubuntu:~/modmesh$ pytest -v
================================================ test session starts ================================================
platform linux -- Python 3.8.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/ubuntu/modmesh
collected 22 items                                                                                                  

tests/test_buffer.py::ConcreteBufferBasicTC::test_ConcreteBuffer PASSED                                       [  4%]
tests/test_buffer.py::ConcreteBufferBasicTC::test_ConcreteBuffer_from_ndarray PASSED                          [  9%]
tests/test_buffer.py::SimpleArrayBasicTC::test_SimpleArray PASSED                                             [ 13%]
tests/test_buffer.py::SimpleArrayBasicTC::test_SimpleArray_from_ndarray PASSED                                [ 18%]
tests/test_buffer.py::SimpleArrayBasicTC::test_SimpleArray_from_ndarray_content PASSED                        [ 22%]
tests/test_buffer.py::SimpleArrayBasicTC::test_SimpleArray_ghost_1d PASSED                                    [ 27%]
tests/test_buffer.py::SimpleArrayBasicTC::test_SimpleArray_ghost_md PASSED                                    [ 31%]
tests/test_buffer.py::SimpleArrayBasicTC::test_SimpleArray_types PASSED                                       [ 36%]
tests/test_grid.py::StaticGridTC::test_ndim PASSED                                                            [ 40%]
tests/test_grid1d.py::StaticGrid1dTC::test_coord PASSED                                                       [ 45%]
tests/test_grid1d.py::StaticGrid1dTC::test_fill PASSED                                                        [ 50%]
tests/test_grid1d.py::StaticGrid1dTC::test_getset PASSED                                                      [ 54%]
tests/test_profile.py::StopWatchTC::test_lap_with_sleep PASSED                                                [ 59%]
tests/test_profile.py::StopWatchTC::test_microsecond_resolution PASSED                                        [ 63%]
tests/test_profile.py::StopWatchTC::test_singleton PASSED                                                     [ 68%]
tests/test_profile.py::WrapperProfilerStatusTC::test_default PASSED                                           [ 72%]
tests/test_profile.py::WrapperProfilerStatusTC::test_singleton PASSED                                         [ 77%]
tests/test_profile.py::TimeRegistryTC::test_empty_report PASSED                                               [ 81%]
tests/test_profile.py::TimeRegistryTC::test_entry PASSED                                                      [ 86%]
tests/test_profile.py::TimeRegistryTC::test_names PASSED                                                      [ 90%]
tests/test_profile.py::TimeRegistryTC::test_singleton PASSED                                                  [ 95%]
tests/test_profile.py::TimeRegistryTC::test_status PASSED                                                     [100%]

================================================ 22 passed in 0.23s =================================================
ubuntu@ubuntu:~/modmesh$ 
```

The interesting part is I failed to print something expected. Not sure it a bug or not yet:

```
ubuntu@ubuntu:~/modmesh$ sudo python3 -c "import modmesh; print(modmesh._modmesh.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/modmesh/modmesh/__init__.py", line 64, in <module>
    from . import _modmesh as _impl  # noqa: F401
ImportError: cannot import name '_modmesh' from partially initialized module 'modmesh' (most likely due to a circular import) (/home/ubuntu/modmesh/modmesh/__init__.py)
```

**Comment by yungyuc** [comment]
> The interesting part is I failed to print something expected. Not sure it a bug or not yet:
> 
> ```
> ubuntu@ubuntu:~/modmesh$ sudo python3 -c "import modmesh; print(modmesh._modmesh.__file__)"
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/ubuntu/modmesh/modmesh/__init__.py", line 64, in <module>
>     from . import _modmesh as _impl  # noqa: F401
> ImportError: cannot import name '_modmesh' from partially initialized module 'modmesh' (most likely due to a circular import) (/home/ubuntu/modmesh/modmesh/__init__.py)
> ```

Could you look into this?  It looks like a misconfiguration of import path.  It is good to confirm of falsify.

**Comment by tai271828** [comment]
> Could you look into this? It looks like a misconfiguration of import path. It is good to confirm of falsify.

Will do!

**Comment by tai271828** [comment]
Back to work on this issue. The recent change of the code base seems to need Qt6 development files for the recent QT viewer. I am still trying to build QT from source since it is too new for debian/ubuntu.

Two approaches for now:
1. Build the QT development files and mvoe forward.
2. Or, checkout the earlier commit e.g. `ed59a256f624dd99ac052ff7b044c0510eb2a7e4` and focus on this issue if it takes me too much time working on 1.

If anyone knows more tips regarding the Qt issue, please let me know. I will appreciate your help!

**Comment by yungyuc** [comment]
> Back to work on this issue. The recent change of the code base seems to need Qt6 development files for the recent QT viewer. I am still trying to build QT from source since it is too new for debian/ubuntu.

It is a misunderstanding that the work for the experimental viewer made modmesh depend on Qt.  The viewer does depend on Qt, but the Python extension module does not.  Building the viewer can be turned off using https://github.com/solvcon/modmesh/blob/68681c7111beb6eaf8489bf1a6ed77aa0167986e/CMakeLists.txt#L14 The CI is also configured so: https://github.com/solvcon/modmesh/blob/68681c7111beb6eaf8489bf1a6ed77aa0167986e/.github/workflows/modmesh_install.yml#L71 It does not seem to be a concern for the columnar array work.  I think we can move on without discussing Qt.

**Comment by tai271828** [comment]
Neat! Thanks for the tip.

Some misc notes from what I found:
1. For Ubuntu developers, please note `the officially supported CMake generator for building Qt is Ninja`[1]. You may need `sudo apt update; sudo apt install ninja-build` to help you build the qt6 when following [the instruction wiki](https://wiki.qt.io/Building_Qt_6_from_Git). For me Ubuntu 20.04.4 could build qt6 tag v6.2.4 successfully.
2. The bisect result of the Qt build issue for me:

```
~/modmesh$ git bisect good
e8edffdcd3b477014d14e98f69b36f437862de16 is the first bad commit
commit e8edffdcd3b477014d14e98f69b36f437862de16
Author: Yung-Yu Chen <yyc@solvcon.net>
Date:   Sun Feb 27 23:16:25 2022 +0800

    Add the stub of drawing a simple 2D mesh using Qt
    
    The Qt module can be turned off by using "BUILD_QT=OFF".
    
    Ref #39 (prototype GUI)
```

I raised another discussion thread to track the Qt discussion https://github.com/solvcon/modmesh/discussions/53 . Let me follow yyc's tip and back to focus on this issue.

[1] https://www.mail-archive.com/interest@qt-project.org/msg36419.html

**Comment by tai271828** [comment]
I did not reproduce the import path issue mentioned [here] with the master code built without Qt[1].

I believe the mis-configuration of the import path came from the mis-installation out of `devenv` flavor stack (I set up my development environment with `devenv`), for example, I did not use `pip3` in my `devenv` flavor to install `pytest`.

Next step:
Go back and work on the array!

[1]
```
~/modmesh$ pytest -v
================================================ test session starts ================================================
platform linux -- Python 3.8.13+, pytest-7.1.1, pluggy-1.0.0 -- /home/ubuntu/devenv/flavors/prime/usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/ubuntu/modmesh
collected 24 items                                                                                                  

tests/test_buffer.py::ConcreteBufferBasicTC::test_ConcreteBuffer PASSED                                       [  4%]
tests/test_buffer.py::ConcreteBufferBasicTC::test_ConcreteBuffer_from_ndarray PASSED                          [  8%]
tests/test_buffer.py::SimpleArrayBasicTC::test_SimpleArray PASSED                                             [ 12%]
tests/test_buffer.py::SimpleArrayBasicTC::test_SimpleArray_from_ndarray PASSED                                [ 16%]
tests/test_buffer.py::SimpleArrayBasicTC::test_SimpleArray_from_ndarray_content PASSED                        [ 20%]
tests/test_buffer.py::SimpleArrayBasicTC::test_SimpleArray_ghost_1d PASSED                                    [ 25%]
tests/test_buffer.py::SimpleArrayBasicTC::test_SimpleArray_ghost_md PASSED                                    [ 29%]
tests/test_buffer.py::SimpleArrayBasicTC::test_SimpleArray_types PASSED                                       [ 33%]
tests/test_grid.py::StaticGridTC::test_ndim PASSED                                                            [ 37%]
tests/test_grid1d.py::StaticGrid1dTC::test_coord PASSED                                                       [ 41%]
tests/test_grid1d.py::StaticGrid1dTC::test_fill PASSED                                                        [ 45%]
tests/test_grid1d.py::StaticGrid1dTC::test_getset PASSED                                                      [ 50%]
tests/test_mesh.py::StaticMeshTC::test_2d_trivial_triangles PASSED                                            [ 54%]
tests/test_mesh.py::StaticMeshTC::test_construct PASSED                                                       [ 58%]
tests/test_profile.py::StopWatchTC::test_lap_with_sleep PASSED                                                [ 62%]
tests/test_profile.py::StopWatchTC::test_microsecond_resolution PASSED                                        [ 66%]
tests/test_profile.py::StopWatchTC::test_singleton PASSED                                                     [ 70%]
tests/test_profile.py::WrapperProfilerStatusTC::test_default PASSED                                           [ 75%]
tests/test_profile.py::WrapperProfilerStatusTC::test_singleton PASSED                                         [ 79%]
tests/test_profile.py::TimeRegistryTC::test_empty_report PASSED                                               [ 83%]
tests/test_profile.py::TimeRegistryTC::test_entry PASSED                                                      [ 87%]
tests/test_profile.py::TimeRegistryTC::test_names PASSED                                                      [ 91%]
tests/test_profile.py::TimeRegistryTC::test_singleton PASSED                                                  [ 95%]
tests/test_profile.py::TimeRegistryTC::test_status PASSED                                                     [100%]

================================================ 24 passed in 0.29s =================================================
```

**Comment by tai271828** [comment]
I verified an approach to build the Python extension module without disabling Qt6 with Ubuntu 22.04 (Jammy). The tip is to install not only the Qt6 core package but also the other necessary Qt6 packages.

**Comment by yungyuc** [comment]
Unassign for lack of activities.

**Comment by yungyuc** [comment]
This request is being refreshed in #339
