### ISSUE TITLE
There should not be unit in the vertical axis in the 1D Euler solver plot

### ISSUE THREAD

**Issue by yungyuc** [solvcon/solvcon#281]
The 1D Euler solver uses non-dimensional equations.  There should not be units in the vertical axis.  There should be only one vertical axis, too.

<img width="1478" alt="image" src="https://github.com/solvcon/modmesh/assets/399122/85a00ae4-d71f-4e7e-bded-806e51458860">

**Comment by yungyuc** [comment]
@j8xixo12 Could you please help fix it or find someone to?

**Comment by j8xixo12** [comment]
I’ll find someone to fix it.

Does only one vertical axis means that the 2 vertical axis on the right hand side need to be removed ?
But if plot only has one vertical axis, the data lines with larger numerical ranges overlay the ones with smaller numerical ranges, making the smaller range lines less visible.

**Comment by yungyuc** [comment]
> I’ll find someone to fix it.
> 
> Does only one vertical axis means that the 2 vertical axis on the right hand side need to be removed ? But if plot only has one vertical axis, the data lines with larger numerical ranges overlay the ones with smaller numerical ranges, making the smaller range lines less visible.

Yes, no more than 1 vertical axis.  Vertical plotting range should not change as the code runs.

To help view small value, zooming should be implement in the viewer.

**Comment by j8xixo12** [comment]
@yungyuc 
This issue has been resolved by #308, I think it can be closed.
However, I integrated [matplotlib navigation toolbar](https://matplotlib.org/3.2.2/users/navigation_toolbar.html) into modmesh instead of self-implement.
Should we create another issue specifically to mention that it should be self-implemented?

**Comment by yungyuc** [comment]
Thanks a lot, @j8xixo12 , let me close this one.

Yes, please create another issue for enhancing the navigation widgets by home-grown code.  If you file it before the sprint, I will bring it there and find hands.
