### ISSUE TITLE
Refactor to consolidate common parts between `ConcreteBuffer` and `BufferExpander`

### ISSUE THREAD

**Issue by yungyuc** [solvcon/solvcon#305]
There are common code between `ConcreteBuffer` (fixed-size buffer manager) and `BufferExpander` (growing buffer manager), e.g., the [`validate_range()`](https://github.com/solvcon/modmesh/blob/3d1944e2342118b62e3349f425b3585a89002b6c/cpp/modmesh/buffer/ConcreteBuffer.hpp#L279C10-L279C24).  Refactoring can make the code more maintainable.  There are 3 types of tasks:

1. Extract the common code to base classes (mixins), or use other ways to share the code.  (No need to overdo it.  Some duplicated code is good for maintenance and debugging.)
2. Unify the type aliases, e.g., [`size_type`](https://github.com/solvcon/modmesh/blob/3d1944e2342118b62e3349f425b3585a89002b6c/cpp/modmesh/buffer/BufferExpander.hpp#L58)
3. Move lengthy code from the header file `ConcreteBuffer.hpp` to the implementation file `ConcreteBuffer.cpp` to save compile time

They may use different PRs for clarity.  This issue is to follow up the discussion at https://github.com/solvcon/modmesh/pull/304#discussion_r1555105830

**Comment by tigercosmos** [comment]
https://github.com/solvcon/modmesh/blob/master/cpp/modmesh/buffer/ConcreteBuffer.hpp#L251C28-L251C36
`allocate` should be able to put into `BufferBase`, though I didn't find a way to make it. the difficult part is the deleted. cc @yungyuc

**Comment by yungyuc** [comment]
The allocation helper `allocate()` is a prototype for a fully-fledge memory manager that is (yet) to be designed for the buffer management.  It can be left there for now.

It is not easy to design a memory manager before the applications mostly emerges.  In the case for modmesh/solvcon, the applications are mesh generation and solution data analysis.

**Comment by yungyuc** [comment]
Refactoring work is done at this stage.
