### ISSUE TITLE
Add Dataframe

### ISSUE THREAD

**Issue by xingularity** [solvcon/solvcon#332]
Add a DataFrame facility. A DataFrame is a two-dimensional, size-mutable tabular data structure with labeled axes (rows and columns). This DataFrame should have following capabilities.

1. Store a size-mutable tabular data.
2. With single row and column index (unsigned integer type).
3. Support limited data types first, primarily numerical.
4. Sub DataFrame selection and assignment by index.
5. Sorting data according to specific column and specify order.
6. Search data in DataFrame and return matched index.

**Comment by yungyuc** [comment]
Thanks @xingularity .  The list includes some features but I did not see any analytical calculations like average, variation, etc.  Could you think of some as a starting point for development?

**Comment by xingularity** [comment]
Hi @yungyuc I thin we can start with the following 6 functions.
* count
* mean
* std
* min
* max
* quantile (provide capabilities to get any quantile)
