### ISSUE TITLE
Document the coding style

### ISSUE THREAD

**Issue by yungyuc** [solvcon/solvcon#350]
We have coding style in modmesh but have not documented it.  We should create one file to document it.  It does not need to be complete, but must be accurate.

**Comment by ThreeMonth03** [comment]
I think we could refer the [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html#Naming),
and write the simpler guide for modmesh.

I will pull the draft by 6/10(Mon.).

In the draft, I expect it will list the guide about naming, comments and formatting.

**Comment by tigercosmos** [comment]
Let me provide some points:
- We are using snake case for functions and variables for non-QT-related code
- need to have `/* end of xxx */` where `xxx` is a namespace or class.
- follow the rule of 5
- follow doxygen comment style
- comment for reference is highly recommend
- class member start with `m_`.
- macro start with `DECL_MM_`.

**Comment by ThreeMonth03** [comment]
> I think we could refer the [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html#Naming), and write the simpler guide for modmesh.
> 
> I will pull the draft by 6/10(Mon.).
> 
> In the draft, I expect it will list the guide about naming, comments and formatting.

Here is a simple draft.
https://github.com/solvcon/modmesh/pull/362#pullrequestreview-2106723203

**Comment by yungyuc** [comment]
@ThreeMonth03 I will try to put together a style guide by following your attempt in #362.

**Comment by ThreeMonth03** [comment]
> @ThreeMonth03 I will try to put together a style guide by following your attempt in #362.

Thank you, I look forward to seeing the guideline.

**Comment by yungyuc** [comment]
Fixed by #394

**Comment by yungyuc** [comment]
I created https://github.com/solvcon/modmesh/discussions/395 for further discussions on the coding style.
