### ISSUE TITLE
[CI] Unittest failed due to unmatch version between pybind11 and numpy on Windows

### ISSUE THREAD

**Issue by terrychan999** [solvcon/solvcon#369]
Unittest failed due to unmatch version between pybind11 and numpy on Windows
https://github.com/solvcon/modmesh/actions/runs/9543001168/job/26298787987

> ```
>   A module that was compiled using NumPy 1.x cannot be run in
>   NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
>   versions of NumPy, modules must be compiled with NumPy 2.0.
>   Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
>   
>   If you are a user of the module, the easiest solution will be to
>   downgrade to 'numpy<2' or try to upgrade the affected module.
>   We expect that some modules will need time to support NumPy 2.
> ```

Unspecifing the version of pybind11 should fix the issue.
https://github.com/solvcon/modmesh/blob/ff4b4d654ab9abc53fe4096bf952e67929f972ac/.github/workflows/devbuild.yml#L483

**Comment by yungyuc** [comment]
@terrychan999 I guess PR #368 also addressed this issue?

**Comment by terrychan999** [comment]
> @terrychan999 I guess PR #368 also addressed this issue?

Yes, I've just unspecified the version of pybind11, also bumped Python version to 3.12 on `build_windows` in PR https://github.com/solvcon/modmesh/pull/368

**Comment by yungyuc** [comment]
Thanks.  Close this issue with PR #368
