### ISSUE TITLE
Typo in README.rst

### ISSUE THREAD

**Issue by ThreeMonth03** [solvcon/solvcon#411]
The subheadings [`Refenreces`](https://github.com/solvcon/modmesh/blob/5cc3cc326ed66b72315f7116ee9f1a34584d69eb/README.rst?plain=1#L28) need fixing.

**Comment by tigercosmos** [comment]
Please go ahead.

**Comment by yungyuc** [comment]
It looks like my bad!  And it looks like simple enough for a new comer to play with.

**Comment by yungyuc** [comment]
Fixed by PR #413.
