### ISSUE TITLE
Enhance the function `CallProfiler::print_statistics` in the profiler.

### ISSUE THREAD

**Issue by ThreeMonth03** [solvcon/solvcon#421]
In the pr #376, we develop a function that can count and print the statistic data in the profiler.

https://github.com/solvcon/modmesh/blob/da4328f3fbfd4cd21fde72a1f6abfd41625daa7c/cpp/modmesh/toggle/RadixTree.cpp#L101-L142

Here is the example of the function shows:
```
                                        7 function calls in 2.40007 seconds

                           Function Name               Call Count           Total Time (s)             Per Call (s)      Cumulative Time (s)             Per Call (s)
                                     bar                        4                  2.00004                 0.500009                  2.00004                 0.500009
                                     baz                        1                 0.800013                 0.800013                 0.200003                 0.200003
                                     foo                        2                  1.20004                 0.600022                 0.200027                 0.100014
```

As you can see, it is useful, but it seems that we could beautify the returned result, such as the following example, which is drew by gpt4:
```
                             7 Function Calls in 2.40007 Seconds

    ---------------------------------------------------------------------------------------------------------------------------------------
    |    Function Name    |    Call Count    |    Total Time (s)    |    Per Call (s)    |    Cumulative Time (s)    |    Per Call (s)    |
    ---------------------------------------------------------------------------------------------------------------------------------------
    |        bar          |        4         |        2.00004       |      0.500009      |           2.00004         |      0.500009      |
    |        baz          |        1         |        0.800013      |      0.800013      |           0.200003        |      0.200003      |
    |        foo          |        2         |        1.20004       |      0.600022      |           0.200027        |      0.100014      |
    ---------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by ThreeMonth03** [comment]
I remember that @dragonwu0919 is learning pybind11 and unittest. @dragonwu0919, could you please beautify the print result of this function?

**Comment by dragonwu0919** [comment]
@ThreeMonth03 sure, that will be a good chance for me to practice

**Comment by dragonwu0919** [comment]
@ThreeMonth03 I have figured out how to re-write this function in general. Yet, may I ask how to directly call this profiler in the terminal? So that I can see whether my code can print out correct profile or not.

**Comment by tigercosmos** [comment]
@dragonwu0919  You can refer to the related code in the "tests" (running pytest) and "gtests" directories. While you run the tests, you can see the output on the terminal.

If you don't know how to run the test, you can refer to how the CI runs.

**Comment by ThreeMonth03** [comment]
> @ThreeMonth03 I have figured out how to re-write this function in general. Yet, may I ask how to directly call this profiler in the terminal? So that I can see whether my code can print out correct profile or not.

@dragonwu0919 You may refer the following part of yaml to print the detail output. It is a good chance for you to trace the CI, GNU make and cmake.

https://github.com/solvcon/modmesh/blob/146d9844b6667fae47ad93eb53bb6863dc6c087b/.github/workflows/devbuild.yml#L431-L442

**Comment by dragonwu0919** [comment]
> > @ThreeMonth03 I have figured out how to re-write this function in general. Yet, may I ask how to directly call this profiler in the terminal? So that I can see whether my code can print out correct profile or not.
> 
> @dragonwu0919 You may refer the following part of yaml to print the detail output. It is a good chance for you to trace the CI, GNU make and cmake.
> 
> https://github.com/solvcon/modmesh/blob/146d9844b6667fae47ad93eb53bb6863dc6c087b/.github/workflows/devbuild.yml#L431-L442

@ThreeMonth03 @tigercosmos Thanks a lot. 

~~I believe I can now see the mechanism behind. Looks like workflow will trigger a `cmake` for gtest. During gtest procedure, `print_statistic` has been called, and therefore I can see the profile printed onto the terminal.~~

Oops... I underestimated the complexity of this topic.

**Comment by yungyuc** [comment]
To make it more interesting, we may also start to plan for plotting the profiling results in the GUI.

**Comment by yungyuc** [comment]
Of course, GUI work uses a separate issue :)

**Comment by ThreeMonth03** [comment]
It seems that @dragonwu0919 is busy now. @Vincent-Lien, are you interested in developing the profiler, the measurement tool for the performance of the program?

**Comment by Vincent-Lien** [comment]
@ThreeMonth03 Yes, I'm interested in developing the profiler. It's a good chance for me to study.

**Comment by ThreeMonth03** [comment]
Thanks, @Vincent-Lien .You optimize the function with issue#436. We would find some follow-up issue later.
