### ISSUE TITLE
[viewer] Add menubar

### ISSUE THREAD

**Issue by yungyuc** [solvcon/solvcon#59]
Add basic menubar to the viewer.

**Comment by yanagiragi** [comment]
Shouldn't be hard. Please let me have a try.

**Comment by yungyuc** [comment]
mac may have some special behaviors.  See https://doc.qt.io/qt-6/qmenubar.html#qmenubar-as-a-global-menu-bar and #90 for more information.

**Comment by yungyuc** [comment]
I forgot to close this issue which is considered as done.
